# Site settings
title: 
email: stephenpickman@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: https://spickman.github.io/serico
url: 
twitter_username: twitter_username
github_username: spickman 

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page/num/"

collections:
  portfolio:
    output: true
    permalink: portfolio/:path/

plugins:
    - jekyll-paginate
